# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Linux
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: sdk
      version: 5.0.x
  - script: dotnet build ./SeekQ.sln
    displayName: 'dotnet build'